#!/bin/bash

echo -e "Meshing from File"

ideasUnvToFoam vane.unv >&1 | tee log.mesh

echo -e "Changing patch type"

changeDictionary >&1 | tee log.changeDictionary

echo -e "Transforming mesh"

transformPoints << EOF
translate=(0 0.1 0)
EOF
